objects:
  - name: hab2|0
    expr_type: rigid_obj_type
  - name: TARGET_hab2|0
    expr_type: goal_type
  - name: ROBOT_0
    expr_type: robot_type

stage_goals: {}
init: 
  - holding(hab2|0, ROBOT_0)

goal:
  expr_type: AND
  sub_exprs:
    - at(hab2|0,TARGET_hab2|0)

solution:
  - nav(hab2|0,ROBOT_0)
  - place(hab2|0,TARGET_hab2|0, ROBOT_0)
